/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.code.vista;

import app.code.common.Paginador;
import app.code.common.TituloTab;
import app.code.controlador.ControladorFactory;
import app.code.vista.general.vistaCatalogos;
import app.code.vista.usuario.CrearEditarUsuario;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.util.Calendar;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Carlos
 */
public class Vista extends javax.swing.JFrame {

    // Declara las variables de interfaz   
    private final Map<Integer, Integer> listaIndices;

    // Declarar variables de datos;
    private final ControladorFactory controladorFactory;
    /**
     * Creates new form Vista
     */
    public Vista() {
        Vista.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        
        listaIndices = new HashMap<>();
        this.setLocationRelativeTo(null);
        this.controladorFactory = ControladorFactory.getInstancia();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        herramietas = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelOpciones = new javax.swing.JPanel();
        lblNavegador = new javax.swing.JLabel();
        lblTM1 = new javax.swing.JLabel();
        btnCobrosFios = new javax.swing.JButton();
        btnEditarUsuario = new javax.swing.JButton();
        PanelPestania = new javax.swing.JTabbedPane();
        PanelInicio = new javax.swing.JPanel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        herramietas.setBackground(new java.awt.Color(177, 175, 175));
        herramietas.setToolTipText("");
        herramietas.setComponentPopupMenu(menu.getComponentPopupMenu());
        herramietas.setPreferredSize(new java.awt.Dimension(734, 40));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout herramietasLayout = new javax.swing.GroupLayout(herramietas);
        herramietas.setLayout(herramietasLayout);
        herramietasLayout.setHorizontalGroup(
            herramietasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, herramietasLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        herramietasLayout.setVerticalGroup(
            herramietasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(herramietasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelOpciones.setBackground(new java.awt.Color(88, 87, 87));
        panelOpciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 200, 200)));

        lblNavegador.setBackground(new java.awt.Color(177, 175, 175));
        lblNavegador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNavegador.setForeground(new java.awt.Color(51, 51, 51));
        lblNavegador.setText("  N A V E G A D O R ");
        lblNavegador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 200, 200)));
        lblNavegador.setOpaque(true);

        lblTM1.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        lblTM1.setForeground(new java.awt.Color(153, 153, 153));
        lblTM1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/linea.png"))); // NOI18N
        lblTM1.setText("ADMINISTRACION");

        btnCobrosFios.setBackground(new java.awt.Color(204, 204, 204));
        btnCobrosFios.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnCobrosFios.setForeground(new java.awt.Color(202, 202, 202));
        btnCobrosFios.setText("CATALGOS");
        btnCobrosFios.setContentAreaFilled(false);
        btnCobrosFios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCobrosFios.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnCobrosFios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCobrosFios.setRequestFocusEnabled(false);
        btnCobrosFios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCobrosFiosMouseEntered(evt);
            }
        });
        btnCobrosFios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCobrosFiosActionPerformed(evt);
            }
        });

        btnEditarUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btnEditarUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        btnEditarUsuario.setForeground(new java.awt.Color(202, 202, 202));
        btnEditarUsuario.setText("EDITAR CREAR USUARIOS");
        btnEditarUsuario.setContentAreaFilled(false);
        btnEditarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnEditarUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btnEditarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEditarUsuario.setRequestFocusEnabled(false);
        btnEditarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarUsuarioMouseEntered(evt);
            }
        });
        btnEditarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addComponent(lblNavegador, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTM1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOpcionesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCobrosFios, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelOpcionesLayout.createSequentialGroup()
                        .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addComponent(lblNavegador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblTM1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCobrosFios, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        PanelPestania.setBackground(new java.awt.Color(204, 204, 204));
        PanelPestania.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(203, 200, 200)));
        PanelPestania.setForeground(new java.awt.Color(51, 51, 51));
        PanelPestania.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        PanelPestania.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 18)); // NOI18N
        PanelPestania.setOpaque(true);
        PanelPestania.setRequestFocusEnabled(false);

        PanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelInicio.setEnabled(false);

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );

        PanelPestania.addTab("  INICIO  ", PanelInicio);

        menu.setBackground(new java.awt.Color(153, 153, 153));
        menu.setBorderPainted(false);

        jMenu1.setText("Archivo");

        jMenuItem1.setText("jMenuItem1");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator1);

        jMenuItem2.setText("jMenuItem2");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        jMenu1.add(jMenuItem3);

        menu.add(jMenu1);

        jMenu2.setText("Edit");
        menu.add(jMenu2);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(PanelPestania)
                .addGap(5, 5, 5))
            .addComponent(herramietas, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(herramietas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelPestania))
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
                Thread.sleep(2);
            } catch (InterruptedException e) {
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        System.out.println(System.lineSeparator());
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        System.out.println("adios");
    }//GEN-LAST:event_formWindowClosed

    private void btnCobrosFiosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCobrosFiosMouseEntered
        btnCobrosFios.setOpaque(true);
        btnCobrosFios.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCobrosFiosMouseEntered

    private void btnCobrosFiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCobrosFiosActionPerformed
        PanelPestania.addTab("", new vistaCatalogos(this.controladorFactory.GENERAL));
        TituloTab titulo = new TituloTab("  CATALOGOS  ");
        titulo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                PanelPestania.remove(PanelPestania.indexOfTabComponent(titulo));
            }
        });
        PanelPestania.setTabComponentAt(PanelPestania.getTabCount() - 1, titulo);
    }//GEN-LAST:event_btnCobrosFiosActionPerformed

    private void btnEditarUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarUsuarioMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarUsuarioMouseEntered

    private void btnEditarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarUsuarioActionPerformed
        // TODO add your handling code here:
        PanelPestania.addTab("", new CrearEditarUsuario(this.controladorFactory.USUARIO));
        TituloTab titulo = new TituloTab("  USUARIOS  ");
        titulo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                PanelPestania.remove(PanelPestania.indexOfTabComponent(titulo));
            }
        });
        PanelPestania.setTabComponentAt(PanelPestania.getTabCount() - 1, titulo);        
    }//GEN-LAST:event_btnEditarUsuarioActionPerformed

    public void cerrarVentana(int v) {
        if(listaIndices.get(v) != null){
        PanelPestania.remove(listaIndices.get(v));
        listaIndices.remove(v);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JTabbedPane PanelPestania;
    private javax.swing.JButton btnCobrosFios;
    private javax.swing.JButton btnEditarUsuario;
    private javax.swing.JPanel herramietas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblNavegador;
    private javax.swing.JLabel lblTM1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables
}
