/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.code.vista.usuario;

import app.code.vista.general.*;
import app.code.common.GeneralExeption;
import app.code.common.JTextFieldLimit;

import app.code.controlador.general.RegistroGeneral;
import app.code.controlador.usuario.ControladorUsuario;
import app.code.modelo.general.Catalogo;
import app.code.modelo.general.TipoCatalogo;
import app.code.modelo.usuario.Usuario;
import java.awt.Color;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import static java.util.concurrent.CompletableFuture.runAsync;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class CrearEditarUsuario extends JFrame {

    private int op;
    private boolean cargarLista;

    /**
     * Consructor de formulario crear/editar Catlogo
     *
     * @param esEditar
     * @param registroGeneral
     */

    private final ControladorUsuario USUARIO;
    
    public CrearEditarUsuario(ControladorUsuario USUARIO) {
        initComponents();
        this.USUARIO=USUARIO;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloC = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        lblT1 = new javax.swing.JLabel();
        lblT2 = new javax.swing.JLabel();
        lblT3 = new javax.swing.JLabel();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        btnSaveU = new javax.swing.JButton();
        btnCleanC = new javax.swing.JButton();
        chxC2 = new javax.swing.JCheckBox();
        sep3 = new javax.swing.JSeparator();
        chxC1 = new javax.swing.JCheckBox();
        txtApellidoUsuario = new javax.swing.JTextField();
        lblT4 = new javax.swing.JLabel();
        chxAdministrador = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTituloC.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        lblTituloC.setForeground(new java.awt.Color(0, 51, 102));
        lblTituloC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/linea.png"))); // NOI18N
        lblTituloC.setText("CREAR USUARIO");

        lblT1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT1.setText("Usuario:");

        lblT2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT2.setText("Contraeña:");
        lblT2.setToolTipText("");

        lblT3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT3.setText("Nombre:");

        txtNombreUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        txtPassword.setDocument(new JTextFieldLimit(100, 2));
        txtPassword.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        txtUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        btnSaveU.setBackground(new java.awt.Color(0, 102, 153));
        btnSaveU.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        btnSaveU.setText("GUARDAR");
        btnSaveU.setToolTipText("Realizar Nueva Transaccion para\\n\nel CLiente");
        btnSaveU.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnSaveU.setContentAreaFilled(false);
        btnSaveU.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSaveU.setRequestFocusEnabled(false);
        btnSaveU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveUMouseExited(evt);
            }
        });
        btnSaveU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUActionPerformed(evt);
            }
        });

        btnCleanC.setBackground(new java.awt.Color(204, 204, 204));
        btnCleanC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/borrar.png"))); // NOI18N
        btnCleanC.setToolTipText("Cancelar Transaccion");
        btnCleanC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCleanC.setContentAreaFilled(false);
        btnCleanC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCleanC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCleanC.setRequestFocusEnabled(false);
        btnCleanC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCleanCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCleanCMouseExited(evt);
            }
        });
        btnCleanC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanCActionPerformed(evt);
            }
        });

        chxC2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        chxC2.setForeground(new java.awt.Color(6, 52, 74));
        chxC2.setText("Segir en la ventana despues de Guardar Datos ");
        chxC2.setRequestFocusEnabled(false);

        chxC1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        chxC1.setForeground(new java.awt.Color(6, 52, 74));
        chxC1.setSelected(true);
        chxC1.setText("Activo");
        chxC1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chxC1.setRequestFocusEnabled(false);

        txtApellidoUsuario.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        lblT4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT4.setText("Apellido:");

        chxAdministrador.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        chxAdministrador.setForeground(new java.awt.Color(6, 52, 74));
        chxAdministrador.setSelected(true);
        chxAdministrador.setText("Administrador");
        chxAdministrador.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chxAdministrador.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCleanC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sep3)
                    .addComponent(chxC2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(btnSaveU, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblT3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(lblT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtPassword)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                                .addComponent(chxC1))
                                            .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtApellidoUsuario)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(chxAdministrador)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chxC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblT1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblT2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblT3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellidoUsuario)
                    .addComponent(lblT4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chxAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chxC2)
                .addGap(9, 9, 9)
                .addComponent(btnSaveU, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveUMouseEntered
        if (btnSaveU.isEnabled()) {
            btnSaveU.setForeground(Color.white);
            btnSaveU.setOpaque(true);
        }
    }//GEN-LAST:event_btnSaveUMouseEntered

    private void btnSaveUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveUMouseExited
        if (btnSaveU.isEnabled()) {
            btnSaveU.setForeground(Color.black);
            btnSaveU.setOpaque(false);
        }
    }//GEN-LAST:event_btnSaveUMouseExited

    private void btnSaveUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUActionPerformed
        if (txtUsuario.getText().trim().isEmpty()
                || txtPassword.getText().trim().isEmpty()
                || txtNombreUsuario.getText().trim().isEmpty()
                || txtApellidoUsuario.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Asegurese de llenar todos los datos antes de guardar.", " AVISO", JOptionPane.HEIGHT);
        } else {
            crearCliente();
        }

    }//GEN-LAST:event_btnSaveUActionPerformed

    private void crearCliente() {

        Usuario user = new Usuario(null, true);

        String usuario = txtUsuario.getText();
        String password = txtPassword.getText();
        String nombre = txtNombreUsuario.getText();
        String apellido = txtApellidoUsuario.getText();
        boolean administrador = chxAdministrador.isSelected();

        user.setUsuario(usuario);
        user.setContrasenia(password);
        user.setNombre(nombre);
        user.setApellido(apellido);
        user.setEsAdmin(administrador);

        JOptionPane.showMessageDialog(null, "Catalgo agreagdo satisfactoriamente!", "INFO", JOptionPane.INFORMATION_MESSAGE);
        limpiar();
        if (!chxC2.isSelected()) {
            dispose();
        }

    }

    public void limpiar() {
        txtNombreUsuario.setText("");
        txtPassword.setText("");
        txtUsuario.setText("");
        txtApellidoUsuario.setText("");
        chxC1.setSelected(false);
        chxAdministrador.setSelected(false);
    }

    private void btnCleanCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanCMouseEntered
        btnCleanC.setOpaque(true);
    }//GEN-LAST:event_btnCleanCMouseEntered

    private void btnCleanCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanCMouseExited
        btnCleanC.setOpaque(false);
    }//GEN-LAST:event_btnCleanCMouseExited

    private void btnCleanCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanCActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCleanCActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!txtPassword.getText().trim().isEmpty() || !txtNombreUsuario.getText().trim().isEmpty() || !txtUsuario.getText().trim().isEmpty()) {
            op = JOptionPane.showConfirmDialog(null, "No ha guardado los datos Ingresados\n"
                    + "Desea cerrar la ventana de todos modos?",
                    " AVISO", JOptionPane.HEIGHT);
            if (op == JOptionPane.OK_OPTION) {
                this.dispose();
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanC;
    private javax.swing.JButton btnSaveU;
    private javax.swing.JCheckBox chxAdministrador;
    private javax.swing.JCheckBox chxC1;
    private javax.swing.JCheckBox chxC2;
    private javax.swing.JLabel lblT1;
    private javax.swing.JLabel lblT2;
    private javax.swing.JLabel lblT3;
    private javax.swing.JLabel lblT4;
    private javax.swing.JLabel lblTituloC;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTextField txtApellidoUsuario;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
