/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.code.vista.usuario;

import app.code.vista.general.*;
import app.code.common.GeneralExeption;
import app.code.common.JTextFieldLimit;

import app.code.controlador.general.RegistroGeneral;
import app.code.modelo.general.Catalogo;
import app.code.modelo.general.TipoCatalogo;
import java.awt.Color;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import static java.util.concurrent.CompletableFuture.runAsync;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class CrearEditarUsuario extends JFrame {

    private final RegistroGeneral registroGeneral;
    
    private int op;
    private boolean cargarLista;
    
    /**
     * Consructor de formulario crear/editar Catlogo
     * @param esEditar
     * @param registroGeneral 
     */
    public CrearEditarUsuario(boolean esEditar, RegistroGeneral registroGeneral) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.registroGeneral = registroGeneral;
    }
    
    
    private void cargargDataInicial(){
        this.cargarLista = true;
        CompletableFuture.supplyAsync(()->{ 
            return registroGeneral.obtenerListaTiposCatalogos(); 
        }).thenAccept(res -> {
            res.forEach((tipo) -> {
                
            });
        }).thenRun(() -> {this.cargarLista = false;});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloC = new javax.swing.JLabel();
        sep1 = new javax.swing.JSeparator();
        lblT1 = new javax.swing.JLabel();
        lblT2 = new javax.swing.JLabel();
        lblT3 = new javax.swing.JLabel();
        txtDescripcionCat = new javax.swing.JTextField();
        txtNombreCat = new javax.swing.JTextField();
        txtCodigoCat = new javax.swing.JTextField();
        btnSaveC = new javax.swing.JButton();
        btnCleanC = new javax.swing.JButton();
        chxC2 = new javax.swing.JCheckBox();
        sep3 = new javax.swing.JSeparator();
        chxC1 = new javax.swing.JCheckBox();
        txtDescripcionCat1 = new javax.swing.JTextField();
        lblT4 = new javax.swing.JLabel();
        chxC3 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTituloC.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        lblTituloC.setForeground(new java.awt.Color(0, 51, 102));
        lblTituloC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTituloC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/linea.png"))); // NOI18N
        lblTituloC.setText("CREAR USUARIO");

        lblT1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT1.setText("Usuario:");

        lblT2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT2.setText("Contraeña:");
        lblT2.setToolTipText("");

        lblT3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT3.setText("Nombre:");

        txtDescripcionCat.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        txtNombreCat.setDocument(new JTextFieldLimit(100, 2));
        txtNombreCat.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        txtCodigoCat.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        btnSaveC.setBackground(new java.awt.Color(0, 102, 153));
        btnSaveC.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        btnSaveC.setText("GUARDAR");
        btnSaveC.setToolTipText("Realizar Nueva Transaccion para\\n\nel CLiente");
        btnSaveC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnSaveC.setContentAreaFilled(false);
        btnSaveC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSaveC.setRequestFocusEnabled(false);
        btnSaveC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveCMouseExited(evt);
            }
        });
        btnSaveC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveCActionPerformed(evt);
            }
        });

        btnCleanC.setBackground(new java.awt.Color(204, 204, 204));
        btnCleanC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/borrar.png"))); // NOI18N
        btnCleanC.setToolTipText("Cancelar Transaccion");
        btnCleanC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCleanC.setContentAreaFilled(false);
        btnCleanC.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCleanC.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCleanC.setRequestFocusEnabled(false);
        btnCleanC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCleanCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCleanCMouseExited(evt);
            }
        });
        btnCleanC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanCActionPerformed(evt);
            }
        });

        chxC2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        chxC2.setForeground(new java.awt.Color(6, 52, 74));
        chxC2.setText("Segir en la ventana despues de Guardar Datos ");
        chxC2.setRequestFocusEnabled(false);

        chxC1.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        chxC1.setForeground(new java.awt.Color(6, 52, 74));
        chxC1.setSelected(true);
        chxC1.setText("Activo");
        chxC1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chxC1.setRequestFocusEnabled(false);

        txtDescripcionCat1.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N

        lblT4.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        lblT4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblT4.setText("Apellido:");

        chxC3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        chxC3.setForeground(new java.awt.Color(6, 52, 74));
        chxC3.setSelected(true);
        chxC3.setText("Administrador");
        chxC3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        chxC3.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTituloC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCleanC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sep3)
                    .addComponent(chxC2, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(btnSaveC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblT4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblT3, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                    .addComponent(lblT2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblT1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombreCat)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCodigoCat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                                .addComponent(chxC1))
                                            .addComponent(txtDescripcionCat, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDescripcionCat1)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(chxC3)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTituloC, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chxC1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblT1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCodigoCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblT2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(lblT3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDescripcionCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDescripcionCat1)
                    .addComponent(lblT4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chxC3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chxC2)
                .addGap(9, 9, 9)
                .addComponent(btnSaveC, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveCMouseEntered
        if (btnSaveC.isEnabled()) {
            btnSaveC.setForeground(Color.white);
            btnSaveC.setOpaque(true);
        }
    }//GEN-LAST:event_btnSaveCMouseEntered

    private void btnSaveCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveCMouseExited
        if (btnSaveC.isEnabled()) {
            btnSaveC.setForeground(Color.black);
            btnSaveC.setOpaque(false);
        }
    }//GEN-LAST:event_btnSaveCMouseExited

    private void btnSaveCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveCActionPerformed
        if (txtNombreCat.getText().trim().isEmpty() || 
            txtDescripcionCat.getText().trim().isEmpty() || 
            txtCodigoCat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Asegurese de llenar todos los datos antes de guardar.", " AVISO", JOptionPane.HEIGHT);
        } else {
            crearCliente();
        }

    }//GEN-LAST:event_btnSaveCActionPerformed

    private void crearCliente() {
        
        
            JOptionPane.showMessageDialog(null, "Catalgo agreagdo satisfactoriamente!", "INFO", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
            if (!chxC2.isSelected()){
                dispose();
            }
        
 
    }

    public void limpiar() {
        txtDescripcionCat.setText("");
        txtCodigoCat.setText("");
        txtNombreCat.setText("");
    }
    
    private void btnCleanCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanCMouseEntered
        btnCleanC.setOpaque(true);
    }//GEN-LAST:event_btnCleanCMouseEntered

    private void btnCleanCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanCMouseExited
        btnCleanC.setOpaque(false);
    }//GEN-LAST:event_btnCleanCMouseExited

    private void btnCleanCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanCActionPerformed
        limpiar();
    }//GEN-LAST:event_btnCleanCActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (!txtNombreCat.getText().trim().isEmpty() || !txtDescripcionCat.getText().trim().isEmpty() || !txtCodigoCat.getText().trim().isEmpty()) {
            op = JOptionPane.showConfirmDialog(null, "No ha guardado los datos Ingresados\n"
                    + "Desea cerrar la ventana de todos modos?",
                    " AVISO", JOptionPane.HEIGHT);
            if (op == JOptionPane.OK_OPTION) {
                this.dispose();
            }
        } else {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanC;
    private javax.swing.JButton btnSaveC;
    private javax.swing.JCheckBox chxC1;
    private javax.swing.JCheckBox chxC2;
    private javax.swing.JCheckBox chxC3;
    private javax.swing.JLabel lblT1;
    private javax.swing.JLabel lblT2;
    private javax.swing.JLabel lblT3;
    private javax.swing.JLabel lblT4;
    private javax.swing.JLabel lblTituloC;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTextField txtCodigoCat;
    private javax.swing.JTextField txtDescripcionCat;
    private javax.swing.JTextField txtDescripcionCat1;
    private javax.swing.JTextField txtNombreCat;
    // End of variables declaration//GEN-END:variables
}
