/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.code.vista.contabilidad;

import app.code.controlador.contabilidad.ControladorCuentaContable;
import app.code.controlador.contabilidad.LogicaNegocioContabilidad;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author fanny
 */
public class ListaCuentaContable extends javax.swing.JPanel {

    private final ControladorCuentaContable controladorCuentaContable;
    private final DefaultTableModel modelTablaCatalgos;
    private boolean cargarLista;
    /**
     * Creates new form vistaCatalogos
     * @param registroGeneral
     */
    public ListaCuentaContable(ControladorCuentaContable controladorCuentaContable) {
        initComponents();
         // Inicializa el controlador
        this.controladorCuentaContable = controladorCuentaContable;
       
        // Inicializa el progres bar
        this.cargarLista = false;
        pgbCargador.setVisible(true);
        pgbCargador.setIndeterminate(this.cargarLista);
        pgbCargador.setStringPainted(this.cargarLista);
        pgbCargador.setString("Cargango..");
        
        // Inicializa los datos en la tabla
        modelTablaCatalgos = (DefaultTableModel) tblListaCuenta.getModel();
        //tblListaCatalogos.getColumn("ACCION").setCellEditor(new DefaultCellEditor(new JButton()));
        listarCatalogos();
        //registroGeneral.obtenerCatalogos(); 
    }

//    public ListaCuentaContable(RegistroGeneral regitroGeneral) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }
    
    private void listarCatalogos(){
//        // Obtiene la lista de catalgos
//        this.cargarLista = true;
//        CompletableFuture.supplyAsync(()-> { 
//           // return registroContable.obtenerCatalogosPorRango("", 1); 
//        }).thenAccept(listaCatalogos -> {
//            int index = 0;
//            modelTablaCatalgos.setNumRows(0);
//            for ( Tuple catalogo: listaCatalogos ) {
//                modelTablaCatalgos.addRow(new Object[]{
//                    "", 
//                    "" + ++index, 
//                    catalogo.get(2), 
//                    catalogo.get(3), 
//                    catalogo.get(4), 
//                    "[ " + catalogo.get(5) + " ] - " + catalogo.get(6)
//                });
//            }
//        }).thenRun(() -> {this.cargarLista = false;});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaCuenta = new javax.swing.JTable();
        sep1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btnActualizarTabl = new javax.swing.JButton();
        btnCrearCuenta = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jpnHead = new javax.swing.JPanel();
        sep2 = new javax.swing.JSeparator();
        txtBuscarCuenta = new javax.swing.JTextField();
        btnBuscarCuenta = new javax.swing.JButton();
        jpnFooter = new javax.swing.JPanel();
        sep3 = new javax.swing.JSeparator();
        pgbCargador = new javax.swing.JProgressBar();
        paginador1 = new app.code.common.Paginador();

        tblListaCuenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Accion", "Index", "CODIGO", "NOMBRE", "DESCRIPCION", "ES_TOTAL"
            }
        ));
        jScrollPane1.setViewportView(tblListaCuenta);

        sep1.setForeground(new java.awt.Color(204, 204, 204));
        sep1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        btnActualizarTabl.setText("+");
        btnActualizarTabl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarTablActionPerformed(evt);
            }
        });

        btnCrearCuenta.setText("+");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnActualizarTabl, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnActualizarTabl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnCrearCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jpnHead.setBackground(new java.awt.Color(210, 228, 238));

        sep2.setForeground(new java.awt.Color(204, 204, 204));
        sep2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtBuscarCuenta.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        txtBuscarCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCuentaKeyReleased(evt);
            }
        });

        btnBuscarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/search.png"))); // NOI18N
        btnBuscarCuenta.setToolTipText("");
        btnBuscarCuenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBuscarCuenta.setContentAreaFilled(false);
        btnBuscarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBuscarCuenta.setFocusPainted(false);
        btnBuscarCuenta.setRequestFocusEnabled(false);
        btnBuscarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCuentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnHeadLayout = new javax.swing.GroupLayout(jpnHead);
        jpnHead.setLayout(jpnHeadLayout);
        jpnHeadLayout.setHorizontalGroup(
            jpnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHeadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnHeadLayout.setVerticalGroup(
            jpnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sep2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnHeadLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jpnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtBuscarCuenta)
                    .addComponent(btnBuscarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2))
        );

        jpnFooter.setBackground(new java.awt.Color(210, 228, 238));

        sep3.setForeground(new java.awt.Color(204, 204, 204));
        sep3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpnFooterLayout = new javax.swing.GroupLayout(jpnFooter);
        jpnFooter.setLayout(jpnFooterLayout);
        jpnFooterLayout.setHorizontalGroup(
            jpnFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paginador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pgbCargador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jpnFooterLayout.setVerticalGroup(
            jpnFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sep3)
            .addGroup(jpnFooterLayout.createSequentialGroup()
                .addComponent(paginador1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnFooterLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pgbCargador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(jpnFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jpnFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarTablActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarTablActionPerformed

    }//GEN-LAST:event_btnActualizarTablActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
//          CrearEditarCuentaContable crearEditarCuentaContable, = new CrearEditarCuentaContable(true, registroGeneral);
//        crearEditarCatalogo.setVisible(true);
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscarCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCuentaKeyReleased
        //        if (cbxBuscarC.getSelectedIndex() == 0) {
            //                listarN(controlU.listaCbuscar(txtBuscarC.getText()));
            //                if (modelL.getSize() > 0) {
                //                    listaNombresC.setSelectedIndex(0);
                //                }
            //            }
    }//GEN-LAST:event_txtBuscarCuentaKeyReleased

    private void btnBuscarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCuentaActionPerformed

    }//GEN-LAST:event_btnBuscarCuentaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarTabl;
    private javax.swing.JButton btnBuscarCuenta;
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnFooter;
    private javax.swing.JPanel jpnHead;
    private app.code.common.Paginador paginador1;
    private javax.swing.JProgressBar pgbCargador;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTable tblListaCuenta;
    private javax.swing.JTextField txtBuscarCuenta;
    // End of variables declaration//GEN-END:variables
}
