/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.code.vista.general;
import app.code.common.ModelAcctionTable;
import app.code.common.PanelAcctionTable;
import app.code.controlador.general.LogicaNegocioGeneral;
import app.code.modelo.general.Catalogo;
import app.code.utils.TiposAccion;
import java.awt.Color;
import java.util.concurrent.CompletableFuture;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Carlos
 */
public class ListaCatalogos extends javax.swing.JPanel {
 
    private final LogicaNegocioGeneral registroGeneral;
    private final DefaultTableModel modelTablaCatalgos;
    private boolean cargarLista;
    /**
     * Creates new form vistaCatalogos
     * @param registroGeneral
     */
    public ListaCatalogos(LogicaNegocioGeneral registroGeneral) {
        // Iniciliza los componentes
        initComponents();
              
        // Inicializa el controlador
        this.registroGeneral = registroGeneral;
       
        // Inicializa el progres bar
        this.cargarLista = false;
        pgbCargador.setVisible(true);
        pgbCargador.setIndeterminate(this.cargarLista);
        pgbCargador.setStringPainted(this.cargarLista);
        pgbCargador.setString("Cargango..");
        
        this.buscardorTabla.setAccion((criterio) -> {
            System.out.println(criterio);
        });
        // Inicializa los datos en la tabla
        modelTablaCatalgos = (DefaultTableModel) tblListaCatalogos.getModel();
        ModelAcctionTable<JPanel> cellRenderModel = new ModelAcctionTable();
        tblListaCatalogos.getColumnModel().getColumn(0).setCellRenderer(cellRenderModel);
        tblListaCatalogos.getColumnModel().getColumn(0).setCellEditor(cellRenderModel);
        listarCatalogos();
    }
    
    private void listarCatalogos(){
        // Obtiene la lista de catalgos
        this.cargarLista = true;
        CompletableFuture.supplyAsync(() -> { 
            return registroGeneral.obtenerCatalogosPorRango("", 1); 
        }).thenAccept(listaCatalogos -> {
            int index = 0;
            modelTablaCatalgos.setNumRows(0);
            for ( Catalogo catalogo: listaCatalogos ) {
                PanelAcctionTable panelAccion = new PanelAcctionTable();
                panelAccion.agregarAccion(TiposAccion.ELIMINAR, () -> { 
                    // this.eliminar
                });
                panelAccion.agregarActivar(catalogo.getActivo(), () -> { 
                    System.out.println("hola2 ");
                });
                panelAccion.agregarAccion(TiposAccion.EDITAR, () -> { 
                    System.out.println("hola3 ");
                });
                modelTablaCatalgos.addRow(new Object[]{
                    panelAccion, 
                    "" + ++index, 
                    catalogo.getCodigo(), 
                    catalogo.getNombre(), 
                    catalogo.getDescripcion(), 
                    catalogo.getTipoCatalogo()
                });
            }
        }).thenRun(() -> {this.cargarLista = false;});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sep1 = new javax.swing.JSeparator();
        jpnMain = new javax.swing.JScrollPane();
        tblListaCatalogos = new javax.swing.JTable();
        jpnHead = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btngregarC = new javax.swing.JButton();
        btnCleanC1 = new javax.swing.JButton();
        buscardorTabla = new app.code.common.searchTable();
        jpnFooter = new javax.swing.JPanel();
        sep3 = new javax.swing.JSeparator();
        pgbCargador = new javax.swing.JProgressBar();
        paginador1 = new app.code.common.Paginador();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);

        sep1.setForeground(new java.awt.Color(204, 204, 204));
        sep1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jpnMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jpnMain.setAutoscrolls(true);
        jpnMain.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblListaCatalogos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblListaCatalogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ACCION", "INDEX", "CODIGO", "NOMBRE", "DESCRIPCION", "TIPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblListaCatalogos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblListaCatalogos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tblListaCatalogos.setFocusable(false);
        tblListaCatalogos.setGridColor(new Color(224,224,224));
        tblListaCatalogos.setRowHeight(24);
        tblListaCatalogos.setSelectionBackground(new java.awt.Color(201, 201, 201));
        tblListaCatalogos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblListaCatalogos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblListaCatalogos.getTableHeader().setResizingAllowed(false);
        tblListaCatalogos.getTableHeader().setReorderingAllowed(false);
        tblListaCatalogos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblListaCatalogosMouseReleased(evt);
            }
        });
        jpnMain.setViewportView(tblListaCatalogos);
        if (tblListaCatalogos.getColumnModel().getColumnCount() > 0) {
            tblListaCatalogos.getColumnModel().getColumn(0).setMinWidth(55);
            tblListaCatalogos.getColumnModel().getColumn(0).setPreferredWidth(70);
            tblListaCatalogos.getColumnModel().getColumn(0).setMaxWidth(85);
            tblListaCatalogos.getColumnModel().getColumn(1).setMinWidth(50);
            tblListaCatalogos.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblListaCatalogos.getColumnModel().getColumn(1).setMaxWidth(50);
            tblListaCatalogos.getColumnModel().getColumn(2).setMinWidth(100);
            tblListaCatalogos.getColumnModel().getColumn(2).setMaxWidth(100);
            tblListaCatalogos.getColumnModel().getColumn(4).setResizable(false);
            tblListaCatalogos.getColumnModel().getColumn(5).setMinWidth(200);
            tblListaCatalogos.getColumnModel().getColumn(5).setMaxWidth(300);
        }
        tblListaCatalogos.getAccessibleContext().setAccessibleDescription("");

        jpnHead.setBackground(new java.awt.Color(210, 228, 238));

        jPanel1.setOpaque(false);

        btngregarC.setBackground(new java.awt.Color(0, 51, 102));
        btngregarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/add.png"))); // NOI18N
        btngregarC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btngregarC.setContentAreaFilled(false);
        btngregarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btngregarC.setFocusPainted(false);
        btngregarC.setRequestFocusEnabled(false);
        btngregarC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btngregarCMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btngregarCMouseExited(evt);
            }
        });
        btngregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngregarCActionPerformed(evt);
            }
        });

        btnCleanC1.setBackground(new java.awt.Color(204, 204, 204));
        btnCleanC1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/app/resource/imagen/refresh.png"))); // NOI18N
        btnCleanC1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnCleanC1.setContentAreaFilled(false);
        btnCleanC1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCleanC1.setFocusPainted(false);
        btnCleanC1.setRequestFocusEnabled(false);
        btnCleanC1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCleanC1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCleanC1MouseExited(evt);
            }
        });
        btnCleanC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanC1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(btnCleanC1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btngregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCleanC1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btngregarC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnHeadLayout = new javax.swing.GroupLayout(jpnHead);
        jpnHead.setLayout(jpnHeadLayout);
        jpnHeadLayout.setHorizontalGroup(
            jpnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHeadLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(buscardorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnHeadLayout.setVerticalGroup(
            jpnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHeadLayout.createSequentialGroup()
                .addGroup(jpnHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnHeadLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(buscardorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jpnFooter.setBackground(new java.awt.Color(210, 228, 238));

        sep3.setForeground(new java.awt.Color(204, 204, 204));
        sep3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jpnFooterLayout = new javax.swing.GroupLayout(jpnFooter);
        jpnFooter.setLayout(jpnFooterLayout);
        jpnFooterLayout.setHorizontalGroup(
            jpnFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sep3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paginador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pgbCargador, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );
        jpnFooterLayout.setVerticalGroup(
            jpnFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sep3)
            .addGroup(jpnFooterLayout.createSequentialGroup()
                .addComponent(paginador1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnFooterLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(pgbCargador, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sep1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE))
            .addComponent(jpnHead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jpnHead, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(sep1))
                .addComponent(jpnFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblListaCatalogosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListaCatalogosMouseReleased
        
    }//GEN-LAST:event_tblListaCatalogosMouseReleased

    private void btngregarCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngregarCMouseEntered
        btngregarC.setOpaque(true);
    }//GEN-LAST:event_btngregarCMouseEntered

    private void btngregarCMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngregarCMouseExited
        btngregarC.setOpaque(false);
    }//GEN-LAST:event_btngregarCMouseExited

    private void btngregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngregarCActionPerformed
        new CrearEditarCatalogo(cargarLista, registroGeneral).setVisible(true);
    }//GEN-LAST:event_btngregarCActionPerformed

    private void btnCleanC1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanC1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanC1MouseEntered

    private void btnCleanC1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCleanC1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanC1MouseExited

    private void btnCleanC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCleanC1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanC1;
    private javax.swing.JButton btngregarC;
    private app.code.common.searchTable buscardorTabla;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jpnFooter;
    private javax.swing.JPanel jpnHead;
    private javax.swing.JScrollPane jpnMain;
    private app.code.common.Paginador paginador1;
    private javax.swing.JProgressBar pgbCargador;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep3;
    private javax.swing.JTable tblListaCatalogos;
    // End of variables declaration//GEN-END:variables
}
