/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app.code.vista.general;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.border.Border;
/**
 *
 * @author Carlos
 */
public class vistaCatalogos extends javax.swing.JPanel {
    
    private final Cursor cursor;
    private final Border borde;
    private final Font letra;
    private final Color color;
    
    /**
     * Creates new form vistaCatalogos
     */
    public vistaCatalogos() {
        borde = javax.swing.BorderFactory.createLineBorder(new Color(207, 214, 220));
        cursor = new Cursor(Cursor.HAND_CURSOR);
        letra = new Font("Tahoma", 1, 10);
        color = new java.awt.Color(153, 153, 153);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sep1 = new javax.swing.JSeparator();
        scrollL = new javax.swing.JScrollPane();
        tablaTransacciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        sep2 = new javax.swing.JSeparator();
        txtBuscarC = new javax.swing.JTextField();
        btnBuscarC = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        sep1.setForeground(new java.awt.Color(204, 204, 204));
        sep1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        scrollL.setBorder(borde);
        scrollL.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scrollL.setPreferredSize(null);

        tablaTransacciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tablaTransacciones.setFont(letra);
        tablaTransacciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD.", "FECHA", "CUENTA", "MONTO", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaTransacciones.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tablaTransacciones.setCursor(cursor);
        tablaTransacciones.setGridColor(color);
        tablaTransacciones.setRowHeight(20);
        tablaTransacciones.setSelectionBackground(color);
        tablaTransacciones.getTableHeader().setResizingAllowed(false);
        tablaTransacciones.getTableHeader().setReorderingAllowed(false);
        tablaTransacciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tablaTransaccionesMouseReleased(evt);
            }
        });
        scrollL.setViewportView(tablaTransacciones);

        jPanel1.setBackground(new java.awt.Color(210, 228, 238));

        sep2.setForeground(new java.awt.Color(204, 204, 204));
        sep2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        txtBuscarC.setFont(letra);
        txtBuscarC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarCKeyReleased(evt);
            }
        });

        btnBuscarC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        btnBuscarC.setContentAreaFilled(false);
        btnBuscarC.setCursor(cursor);
        btnBuscarC.setOpaque(true);
        btnBuscarC.setRequestFocusEnabled(false);
        btnBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sep2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sep2)
            .addComponent(btnBuscarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(txtBuscarC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sep1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollL, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sep1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(scrollL, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                        .addGap(6, 6, 6))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tablaTransaccionesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaTransaccionesMouseReleased
        
    }//GEN-LAST:event_tablaTransaccionesMouseReleased

    private void txtBuscarCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarCKeyReleased
//        if (!txtBuscarC.getText().isEmpty()) {
//            if (cbxBuscarC.getSelectedIndex() == 0) {
//                listarN(controlU.listaCbuscar(txtBuscarC.getText()));
//                if (modelL.getSize() > 0) {
//                    listaNombresC.setSelectedIndex(0);
//                }
//            }
//        } else {
//            modelL.removeAllElements();
//        }
    }//GEN-LAST:event_txtBuscarCKeyReleased

    private void btnBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCActionPerformed

    }//GEN-LAST:event_btnBuscarCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scrollL;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JTable tablaTransacciones;
    private javax.swing.JTextField txtBuscarC;
    // End of variables declaration//GEN-END:variables
}
